# Generated by Django 3.1.7 on 2021-02-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('semester', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('grade', models.IntegerField(blank=True)),
                ('attempt', models.IntegerField(blank=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('OA', 'Oral Assessment'), ('WA', 'Written Assessment'), ('EA', 'Early Assessment'), ('AA', 'Alternative Assessment'), ('SA', 'Standard Assessment')], default='SA', max_length=32)),
                ('assessment_date', models.DateTimeField()),
                ('target_grade', models.IntegerField(blank=True)),
                ('requirements', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.module')),
            ],
        ),
    ]
